### ISSUE TITLE
KeyError: "tag 'NH' not present"

### ISSUE THREAD

**Issue by tuhulab** [grst/bd_rhapsody_velocyto#1]
I get error tag 'NH' not present. Any advice?

```
[tuhu@g-12-l0001 e2fc79a3db00d5ca7a78bafec53799]$ cat .command.err
INFO:    Converting SIF file to temporary sandbox...
[E::idx_find_and_load] Could not retrieve index file for '/home/projects/cu_10181/people/tuhu/bd_rhapsody_velocyto/work/f0/e2fc79a3db00d5ca7a78bafec53799/B_sort.for_velocyto.bam'
[E::idx_find_and_load] Could not retrieve index file for '/home/projects/cu_10181/people/tuhu/bd_rhapsody_velocyto/work/f0/e2fc79a3db00d5ca7a78bafec53799/B_sort.for_velocyto.bam'
/usr/local/lib/python3.8/site-packages/loompy/view_manager.py:23: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if type(slice_) is not tuple or len(slice_) is not 2:
Traceback (most recent call last):
  File "/usr/local/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/velocyto/commands/run.py", line 113, in run
    return _run(bamfile=bamfile, gtffile=gtffile, bcfile=bcfile, outputfolder=outputfolder,
  File "/usr/local/lib/python3.8/site-packages/velocyto/commands/_run.py", line 212, in _run
    exincounter.mark_up_introns(bamfile=bamfile, multimap=multimap)
  File "/usr/local/lib/python3.8/site-packages/velocyto/counter.py", line 657, in mark_up_introns
    for r in self.iter_alignments(bamfile, unique=not multimap):
  File "/usr/local/lib/python3.8/site-packages/velocyto/counter.py", line 258, in iter_alignments
    if unique and read.get_tag("NH") != 1:
  File "pysam/libcalignedsegment.pyx", line 2401, in pysam.libcalignedsegment.AlignedSegment.get_tag
  File "pysam/libcalignedsegment.pyx", line 2440, in pysam.libcalignedsegment.AlignedSegment.get_tag
KeyError: "tag 'NH' not present"
INFO:    Cleaning up image...
[bam_sort_core] merging from 0 files and 35 in-memory blocks...
```

**Comment by grst** [comment]
No idea, sorry. 
Afaik the NH tag is used to identify multimapping reads. You could check with `samtools view` if it is present in the BAM files you've got. 

Probably the version of the rhapsody pipeline you are using is generating BAM files that are slightly different to the ones I got.
